services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    restart: always

  backend:
    build: ./back-end
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:ricky123@postgres:5432/contact_db"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ricky123
      POSTGRES_DB: contact_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: