services:
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    restart: always

  backend:
    build: ./back-end
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:ricky123@postgres:5432/contact_db"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ricky123
      POSTGRES_DB: contact_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin-ricky
      - N8N_BASIC_AUTH_PASSWORD=071224!
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678

volumes:
  pgdata: